<?php

namespace Database\Seeders;

use App\Models\Groceries;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GroceriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        collect([
            [
                'user_id' => 1,
                'name' => 'Apples',
                'description' => 'Red delicious apples',
                'water' => 86,
                'protein' => 0.3,
                'fat' => 0.4,
                'carbohydr' => 14,
                'dietary' => 0,
                'fiber' => 2.3,
                'alcohol' => 0,
                'pufa' => 0.1,
                'cholesterol' => 0,
                'vit_a' => 7,
                'carotene' => 11,
                'vit_e' => 0.6,
                'vit_b1' => 0.03,
                'vit_b2' => 0.04,
                'vit_b6' => 0.1,
                'total_fol_acid' => 5,
                'vit_c' => 8,
                'sodium' => 2,
                'potassium' => 195,
                'magnessium' => 5,
                'phosphorus' => 11,
                'iron' => 0.2,
                'zink' => 0.1
            ],
            [
                'user_id' => 1,
                'name' => 'Bananas',
                'description' => 'Cavendish bananas',
                'water' => 75,
                'protein' => 1.1,
                'fat' => 0.2,
                'carbohydr' => 23,
                'dietary' => 0,
                'fiber' => 2.6,
                'alcohol' => 0,
                'pufa' => 0.1,
                'cholesterol' => 0,
                'vit_a' => 17,
                'carotene' => 26,
                'vit_e' => 0.1,
                'vit_b1' => 0.04,
                'vit_b2' => 0.05,
                'vit_b6' => 0.5,
                'total_fol_acid' => 23,
                'vit_c' => 10,
                'sodium' => 1,
                'potassium' => 358,
                'magnessium' => 27,
                'phosphorus' => 22,
                'iron' => 0.3,
                'zink' => 0.2
            ],[
                'user_id' => 1,
                'name' => 'Broccoli',
                'description' => 'Fresh green broccoli florets',
                'water' => 89,
                'protein' => 2.6,
                'fat' => 0.3,
                'carbohydr' => 7,
                'dietary' => 0,
                'fiber' => 2.4,
                'alcohol' => 0,
                'pufa' => 0.1,
                'cholesterol' => 0,
                'vit_a' => 623,
                'carotene' => 1078,
                'vit_e' => 1.2,
                'vit_b1' => 0.07,
                'vit_b2' => 0.12,
                'vit_b6' => 0.2,
                'total_fol_acid' => 104,
                'vit_c' => 93,
                'sodium' => 30,
                'potassium' => 316,
                'magnessium' => 21,
                'phosphorus' => 66,
                'iron' => 0.7,
                'zink' => 0.4
            ],
            [
                'user_id' => 1,
                'name' => 'Almonds',
                'description' => 'Raw almonds with skin',
                'water' => 5,
                'protein' => 21,
                'fat' => 51,
                'carbohydr' => 14,
                'dietary' => 0,
                'fiber' => 13,
                'alcohol' => 0,
                'pufa' => 12,
                'cholesterol' => 0,
                'vit_a' => 7,
                'carotene' => 0,
                'vit_e' => 26,
                'vit_b1' => 0.2,
                'vit_b2' => 1.4,
                'vit_b6' => 0.1,
                'total_fol_acid' => 44,
                'vit_c' => 0,
                'sodium' => 1,
                'potassium' => 733,
                'magnessium' => 287,
                'phosphorus' => 481,
                'iron' => 3.7,
                'zink' => 3.1
            ],
            [
                'user_id' => 1,
                'name' => 'Brown Rice',
                'description' => 'Long grain brown rice',
                'water' => 12,
                'protein' => 2.6,
                'fat' => 2.9,
                'carbohydr' => 76.2,
                'dietary' => 0,
                'fiber' => 1.8,
                'alcohol' => 0,
                'pufa' => 0.7,
                'cholesterol' => 0,
                'vit_a' => 0,
                'carotene' => 0,
                'vit_e' => 0.1,
                'vit_b1' => 0.41,
                'vit_b2' => 0.03,
                'vit_b6' => 0.51,
                'total_fol_acid' => 8,
                'vit_c' => 0,
                'sodium' => 5,
                'potassium' => 83,
                'magnessium' => 43,
                'phosphorus' => 162,
                'iron' => 0.8,
                'zink' => 1.1
            ],
            [
                'user_id' => 1,
                'name' => 'Sweet Potato',
                'description' => 'Orange flesh sweet potato',
                'water' => 77,
                'protein' => 1.8,
                'fat' => 0.1,
                'carbohydr' => 20.1,
                'dietary' => 0,
                'fiber' => 3,
                'alcohol' => 0,
                'pufa' => 0.1,
                'cholesterol' => 0,
                'vit_a' => 12045,
                'carotene' => 20413,
                'vit_e' => 1.6,
                'vit_b1' => 0.08,
                'vit_b2' => 0.03,
                'vit_b6' => 0.3,
                'total_fol_acid' => 23,
                'vit_c' => 2.5,
                'sodium' => 55,
                'potassium' => 320,
                'magnessium' => 25,
                'phosphorus' => 47,
                'iron' => 0.7,
                'zink' => 0.3
            ],
            [
                'user_id' => 1,
                'name' => 'Spinach',
                'description' => 'Raw spinach leaves',
                'water' => 91,
                'protein' => 3,
                'fat' => 0.4,
                'carbohydr' => 3.6,
                'dietary' => 0,
                'fiber' => 2.2,
                'alcohol' => 0,
                'pufa' => 0.1,
                'cholesterol' => 0,
                'vit_a' => 469,
                'carotene' => 5626,
                'vit_e' => 2,
                'vit_b1' => 0.08,
                'vit_b2' => 0.19,
                'vit_b6' => 0.2,
                'total_fol_acid' => 194,
                'vit_c' => 28,
                'sodium' => 79,
                'potassium' => 558,
                'magnessium' => 79,
                'phosphorus' => 49,
                'iron' => 2.7,
                'zink' => 0.5
            ],
            [
                'user_id' => 1,
                'name' => 'Blueberries',
                'description' => 'Fresh blueberries',
                'water' => 84,
                'protein' => 0.7,
                'fat' => 0.3,
                'carbohydr' => 15,
                'dietary' => 0,
                'fiber' => 2.4,
                'alcohol' => 0,
                'pufa' => 0.1,
                'cholesterol' => 0,
                'vit_a' => 54,
                'carotene' => 96,
                'vit_e' => 0.8,
                'vit_b1' => 0.04,
                'vit_b2' => 0.04,
                'vit_b6' => 0.1,
                'total_fol_acid' => 6,
                'vit_c' => 9.7,
                'sodium' => 1,
                'potassium' => 77,
                'magnessium' => 6,
                'phosphorus' => 12,
                'iron' => 0.3,
                'zink' => 0.2
            ]
        ])->each(fn ($groceries) => Groceries::create($groceries));
    }
}
